apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: crewrescue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: crewrescue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crewrescue
      component: mongo
  template:
    metadata:
      labels:
        app: crewrescue
        component: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_DATABASE
              value: crewrescue
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: crewrescue
spec:
  selector:
    app: crewrescue
    component: mongo
  ports:
    - port: 27017
      targetPort: 27017
